import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";
import {
  BsFillArrowLeftCircleFill,
  BsFillArrowRightCircleFill,
} from "react-icons/bs";
import placeholder from "../public/placeholder.jpg";
import { AiFillStar, AiOutlineStar } from "react-icons/ai";
import { bestSeller } from "./api/dataResort";
import { motion } from "framer-motion";
import Link from "next/link";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <motion.div
      initial={{
        opacity: 0,
      }}
      animate={{
        opacity: 1,
      }}
      transition={{
        duration: 0.8,
      }}
      className={styles.container}
    >
      <Head>
        <title>Resort App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className={styles.carousel_home}>
          <button className={styles.left_arrow_btn}>
            <BsFillArrowLeftCircleFill />
          </button>
          <button className={styles.right_arrow_btn}>
            <BsFillArrowRightCircleFill />
          </button>
        </div>

        <div className={styles.middle_home}>
          <div className={styles.reserve_button_container}>
            <Link href="/reservation">
              <button>Reserve Now!</button>
            </Link>
          </div>

          <h1>Best Rooms/Cottages</h1>

          <div className={styles.best_sell_container}>
            {bestSeller.map((data, i) => {
              return (
                <div className={styles.best_sell_item} key={i}>
                  <Image src={placeholder} className={styles.best_sell_img} />
                  <div className={styles.inner_best_sell}>
                    {data.rate == 5 && (
                      <div className={styles.rating_container}>
                        <AiFillStar />
                        <AiFillStar />
                        <AiFillStar />
                        <AiFillStar />
                        <AiFillStar />
                      </div>
                    )}
                    {data.rate == 4 && (
                      <div className={styles.rating_container}>
                        <AiFillStar />
                        <AiFillStar />
                        <AiFillStar />
                        <AiFillStar />
                        <AiOutlineStar />
                      </div>
                    )}

                    <h3>{data.name}</h3>
                    <h4>{data.type}</h4>
                    <h2>₱ {data.price}.00</h2>
                    <p>View Details</p>
                  </div>
                </div>
              );
            })}
          </div>

          <h3 className={styles.h3_location_map}>Location Map</h3>
          <div className={styles.google_map}>
            <p>Google Map</p>
          </div>
        </div>
      </main>
      <Footer />
    </motion.div>
  );
}
