import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Reservation.module.css";
import ReservationPart1 from "../components/ReservationForm1/ReservationPart1";
import { motion } from "framer-motion";

function reservation() {
  const [addList, SetAddList] = useState([]);
  const [typeForm, setTypeForm] = useState("");
  const [typeFormLocation, setTypeFormLocation] = useState("");
  const [checkIn, setCheckIn] = useState("");
  const [checkOut, setCheckOut] = useState("");
  const [adult, setAdult] = useState(0);
  const [child, setChild] = useState(0);
  const [price, setPrice] = useState(0);
  const [time, setTime] = useState("js");

  const [showPart1, setShowPart1] = useState(false);
  const [showPart2, setShowPart2] = useState(true);
  const [showPart3, setShowPart3] = useState(false);

  return (
    <motion.div
      initial={{
        opacity: 0,
      }}
      animate={{
        opacity: 1,
      }}
      transition={{
        duration: 0.6,
      }}
      className={styles.reservation_container}
    >
      <Head>
        <title>Reservation Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Reservation Process</h1>

      <ReservationPart1
        setShowPart1={setShowPart1}
        setShowPart2={setShowPart2}
        addList={addList}
        SetAddList={SetAddList}
        typeForm={typeForm}
        setTypeForm={setTypeForm}
        typeFormLocation={typeFormLocation}
        setTypeFormLocation={setTypeFormLocation}
        checkIn={checkIn}
        setCheckIn={setCheckIn}
        checkOut={checkOut}
        setCheckOut={setCheckOut}
        adult={adult}
        setAdult={setAdult}
        child={child}
        setChild={setChild}
        price={price}
        setPrice={setPrice}
        time={time}
        setTime={setTime}
      />
    </motion.div>
  );
}

export default reservation;
