import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Reservation.module.css";
import ReservationPart1 from "../components/ReservationForm1/ReservationPart1";
import { motion } from "framer-motion";
import ReservationPart2 from "../components/ReservationForm2/ReservationPart2";
import {
  BsFillArrowLeftCircleFill,
  BsFillArrowRightCircleFill,
} from "react-icons/bs";
import ReservationPart3 from "../components/ReservationForm3/ReservationPart3";

function reservation() {
  const [addList, SetAddList] = useState([]);
  const [typeForm, setTypeForm] = useState("");
  const [typeFormLocation, setTypeFormLocation] = useState("");
  const [checkIn, setCheckIn] = useState("");
  const [checkOut, setCheckOut] = useState("");
  const [adult, setAdult] = useState(0);
  const [child, setChild] = useState(0);
  const [price, setPrice] = useState(0);
  const [time, setTime] = useState("");

  const [showPart1, setShowPart1] = useState(true);
  const [showPart2, setShowPart2] = useState(false);
  const [showPart3, setShowPart3] = useState(false);

  return (
    <motion.div
      initial={{
        opacity: 0,
      }}
      animate={{
        opacity: 1,
      }}
      transition={{
        duration: 0.6,
      }}
      className={styles.reservation_container}
    >
      <Head>
        <title>Reservation Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Reservation Process</h1>

      <div className={styles.top_button_container}>
        {!showPart1 && showPart2 && (
          <button
            onClick={() => {
              setShowPart1(true);
              setShowPart2(false);
            }}
          >
            <BsFillArrowLeftCircleFill />
          </button>
        )}
      </div>

      {showPart1 && (
        <ReservationPart1
          setShowPart1={setShowPart1}
          setShowPart2={setShowPart2}
          addList={addList}
          SetAddList={SetAddList}
          typeForm={typeForm}
          setTypeForm={setTypeForm}
          typeFormLocation={typeFormLocation}
          setTypeFormLocation={setTypeFormLocation}
          checkIn={checkIn}
          setCheckIn={setCheckIn}
          checkOut={checkOut}
          setCheckOut={setCheckOut}
          adult={adult}
          setAdult={setAdult}
          child={child}
          setChild={setChild}
          price={price}
          setPrice={setPrice}
          time={time}
          setTime={setTime}
        />
      )}

      {showPart2 && (
        <ReservationPart2
          setShowPart1={setShowPart1}
          setShowPart2={setShowPart2}
          setShowPart3={setShowPart3}
          addList={addList}
        />
      )}

      {showPart3 && <ReservationPart3 />}
    </motion.div>
  );
}

export default reservation;
